### ISSUE TITLE
platform mismatch for cross compilation

### ISSUE THREAD

**Issue by JasperDeSutter** [PyO3/maturin#200]
When compiling a cffi crate for a different target through a Cargo environment which has been setup for cross-compilation, maturin fails on a platform check.
I'm trying to build a windows cffi package from a linux build system, but maturin tries to get the windows python.exe, which can easily be overruled by the `-i` flag. But when passed a linux python version, maturin crashes with this output:

```sh
$ maturin build -b cffi --target x86_64-pc-windows-gnu -i python3.7

🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Failed to find python interpreter for generating cffi bindings
  Caused by: Failed to get information from the python interpreter at python3.7
  Caused by: sys.platform in python, linux, and the rust target, Target { os: Windows, is_64_bit: true }, don't match ಠ_ಠ
```
I can manually replace the native.so file within the built wheel by a built windows dll file and it works fine on windows. So I'm guessing this is just a limitation within maturin currently.
This check doesn't seem necessary for me, but could probably be wrong for other use-cases. Does it seem feasible to change this behavior?

**Comment by konstin** [comment]
That cross compiling works with cffi and a python interpreter compiled for the host is unexpected, but really nice. I've removed the check so this should work now (I don't have a windows toolchain installed so I can't test). Feel free reopen if any other problem should occur.

**Comment by JasperDeSutter** [comment]
It's still failing with version 0.7.2, but now the error is different:

```
🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Failed to find python interpreter for generating cffi bindings
  Caused by: Failed to get information from the python interpreter at python
  Caused by: A python 3 interpreter on windows does not define abiflags in its sysconfig ಠ_ಠ
```

Possibly this check needs to use `message.platform` instead of `target.is_windows()`?
https://github.com/PyO3/maturin/commit/4fed0aaa1882442284e27ead66001bcd6c5fd1be#diff-fe14ac9493643b24fb25c9f2bd854864R337
I can't tell for sure yet,, but I can look into this later and send a PR if you want.
